services:
  # Backend: FastAPI (no Docker unless you really need it)
  - type: web
    name: qa-eve-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qa-eve-db
          property: connectionString

      - key: PYTHON_VERSION
        value: 3.11.9   # 👈 Force Python version here

      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: "HS256"
      - key: PDF_FOLDER
        value: "data/lesson_pdfs"
      - key: OLLAMA_MODEL
        value: "llama3"
      - key: EMBEDDING_MODEL
        value: "BAAI/bge-base-en-v1.5"
      - key: CHROMA_DB_DIR
        value: "backend/app/chroma_db"
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-3.5-turbo"
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,http://127.0.0.1:3000"

      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_MODEL
        value: "meta-llama/Llama-3-8B-Instruct"

      - key: USE_OPENAI_IF_OLLAMA_FAILS
        value: "true"
      - key: USE_TOGETHER_IF_OLLAMA_FAILS
        value: "false"
